var EMOTION = [
	"I feel like I want to hurt someone",
	"I feel grossed out",
	"I feel nervous",
	"I feel scared",
	"I feel sick",
	"I feel panicked",
	"I feel like all will be okay",
	"I feel disappointed",
	"I feel happy",
	"I feel like Im going to die",
	"I feel like there's something going on",
	"I feel like this could be the end",
	"I feel like Im in trouble",
	"I feel like I could get hurt",
	"I feel hopeful",
	"I feel like a disaster looming",
	"I feel like were about to have fun",
	"I feel like its haunted here",
	"I feel like were in a horror film",
	"I feel whimsical",
	"I feel like im in love",
	"I feel like consuming something",
	"I feel like I should change my clothes",
	"I feel like crying",
	"I feel lucky",
	"I would like to forget this moment",
	"I feel like I should Hide",
	"I feel curiousI feel like competing",
	"I feel annoyed",
	"I feel liked",
	"I feel like Im ready to pounce",
	"I feel like screaming",
	"I feel angry",
	"I feel awkward",
	"I feel embarrassed",
	"I feel dirty",
	"I feel like Im going to pass out",
	"I feel squeamish",
	"I feel like I should say something",
	"I feel affectionate",
	"I feel protective",
	"I feel nostalgic",
	"I feel stimulated",
	"I feel like theres something wrong",
	"I feel like theres a mystery here",
	"I feel excited",
	"I feel my stomach rumbling",
	"I feel like im going to throw up",
	"I feel like I should call the cops",
	"I feel like someone needs my help",
	"I wish I had a camera",
	"I feel like shaking someones hand",
	"I feel like I should spray perfume",
	"I feel like I need a tissue"
	];
var LOCATION = [
	"at the theme park",
	"at my school prom",
	"at the dance club",
	"at the dinner table",
	"in the office building",
	"at the prison",
	"in my time machine",
	"at the zoo",
	"at the convenience store",
	"on my first date",
	"at my party",
	"on the tropical island",
	"in the battle",
	"at the wedding",
	"at the cemetery",
	"in the stadium",
	"at the crime scene",
	"at the bar",
	"around the campfire",
	"in Las Vegas",
	"in the secret hideout",
	"in Europe",
	"in the haunted mansion",
	"on stage",
	"at the movie theatre",
	"at the mall",
	"at the talk show",
	"on the school bus",
	"in America",
	"in the Wild Wild West",
	"on my family vacation",
	"on the couch",
	"at the aquarium",
	"at Area 51",
	"at church",
	"at college",
	"at the fast food restaurant",
	"at the beach",
	"at the motel",
	"in the supermarket",
	"in the bathroom",
	"in outer space",
	"in my bedroom",
	"on the airplane",
	"in the hot tub",
	"in the cafeteria",
	"in the operating room",
	"on my honeymoon",
	"in the classroom",
	"at the retirement home",
	"on the road trip",
	"at the cult gathering",
	"in the distant future",
	"in the laboratory",
	"in an alternate universe"
];
var REASON = [
	"someone said",
	"I figured out",
	"someone said these two words",
	"a sensual woman said",
	"someone announced",
	"someone showed me",
	"I felt someone",
	"someone whispered",
	"someone is wearing",
	"I found out",
	"an old man said",
	"I was touched by",
	"because someone put",
	"someone cast a spell that",
	"a crazy person said",
	"the time traveler said",
	"my psych evaluation said",
	"I hallucinated that",
	"I remembered that",
	"a booming voice said",
	"someone randomly said",
	"that attractive girl turned out to be",
	"my imaginary friend said",
	"mysterious stranger said",
	"it appears that",
	"someone handed me",
	"someone kept saying over and over",
	"I saw",
	"I heard",
	"I picked up",
	"everyone is chanting",
	"everyone is talking about",
	"someone pressed a buttont that",
	"a robot said",
	"something smells like",
	"I overheard someone planning to",
	"a zombie said",
	"a cheerleader said",
	"someone sang a song like this",
	"someone silently said",
	"someone took a bite out of",
	"the voice in my head said",
	"I had a premonition that",
	"someones final words were",
	"someone told me this lie",
	"the internet said",
	"that attractive guy turned out to be",
	"someone is dancing like",
	"someone said... my name is",
	"someone is celebrating",
	"i am covered in",
	"someone made a sound like",
	"someone made a face like this",
	"someone made a gesture like this",
	"I was playng a game called",
	"my power makes everyone",
	"my nemisis said",
	"my doctor said",
	"long story short",
	"someone put",
	"I bought",
	"I stole",
	"I bumped into",
	"the police said",
	"I tried to",
	"I starred at",
	"I started to",
	"I had to",
	"I was not",
	"the slogan was",
	"they wanted me to"
];
function fire(){
		var emotion = EMOTION[Math.floor((Math.random() * EMOTION.length))];
	var location = LOCATION[Math.floor((Math.random() * LOCATION.length))];
	var reason = REASON[Math.floor((Math.random() * REASON.length))];
	document.getElementById("kneejerk1").innerHTML = 
		emotion + " " + location + " because " + reason + "...";	
	reason = REASON[Math.floor((Math.random() * REASON.length))];
	document.getElementById("kneejerk2").innerHTML = 
		emotion + " " + location + " because " + reason + "...";	
	reason = REASON[Math.floor((Math.random() * REASON.length))];
	document.getElementById("kneejerk3").innerHTML = 
		emotion + " " + location + " because " + reason + "...";	
}
fire();
document.body.addEventListener('click', function(){
	fire();
}, true); 

