var EMOTION = [
	"Joyful",
	"Tenderness",
	"Helpless",
	"Defeated",
	"Rageful",
	"Cheerful",
	"Sympathy",
	"Powerless",
	"Bored",
	"Outraged",
	"Content",
	"Adoration",
	"Dreading",
	"Rejected",
	"Hostile",
	"Proud",
	"Fondness",
	"Distrusting",
	"Disillusioned",
	"Bitter",
	"Satisfied",
	"Receptive",
	"Suspicious",
	"Inferior",
	"Hateful",
	"Excited",
	"Interested",
	"Cautious",
	"Confused",
	"Scornful",
	"Amused",
	"Delighted",
	"Disturbed",
	"Grief-stricken",
	"Spiteful",
	"Elated",
	"Shocked",
	"Overwhelmed",
	"Helpless",
	"Vengeful",
	"Enthusiastic",
	"Exhilarated",
	"Uncomfortable",
	"Isolated",
	"Disliked",
	"Optimistic",
	"Dismayed",
	"Guilty",
	"Numb",
	"Resentful",
	"Elated",
	"Amazed",
	"Hurt",
	"Regretful",
	"Trusting",
	"Delighted",
	"Confused",
	"Lonely",
	"Ambivalent",
	"Alienated",
	"Calm",
	"Stunned",
	"Melancholy",
	"Exhausted",
	"Bitter",
	"Relaxed",
	"Interested",
	"Depressed",
	"Insecure",
	"Insulted",
	"Relieved",
	"Intrigued",
	"Hopeless",
	"Disgusted",
	"Indifferent",
	"Hopeful",
	"Absorbed",
	"Sad",
	"Pity",
	"Pleased",
	"Curious",
	"Guilty",
	"Revulsion",
	"Confident",
	"Anticipating",
	"Hurt",
	"Contempt",
	"Brave",
	"Eager",
	"Lonely",
	"Weary",
	"Comfortable",
	"Hesitant",
	"Regretful",
	"Bored",
	"Safe",
	"Fearful",
	"Depressed",
	"Preoccupied",
	"Happy",
	"Anxious",
	"Hopeless",
	"Angry",
	"Love",
	"Worried",
	"Sorrow",
	"Jealous",
	"Lust",
	"Scared",
	"Uncertain",
	"Envious",
	"Aroused",
	"Insecure",
	"Anguished",
	"Annoyed",
	"Tender",
	"Rejected",
	"Disappointed",
	"Humiliated",
	"Compassionate",
	"Horrified",
	"Self conscious",
	"Irritated",
	"Caring",
	"Alarmed",
	"Shamed",
	"Aggravated",
	"Infatuated",
	"Shocked",
	"Embarrassed",
	"Restless",
	"Concern",
	"Panicked",
	"Humiliated",
	"Grumpy",
	"Trust",
	"Afraid",
	"Disgraced",
	"Awkward",
	"Liking",
	"Nervous",
	"Uncomfortable",
	"Exasperated",
	"Attraction",
	"Disoriented",
	"Neglected",
	"Frustrated"
	];
var LOCATION = [
	"airport",
	"amusement park",
	"antique shop",
	"appliance store",
	"arcade",
	"arena",
	"art gallery",
	"art museum",
	"aquarium",
	"army surplus store",
	"auditorium",
	"bakery",
	"bank",
	"bar",
	"barbershop",
	"beauty salon",
	"bed and breakfast",
	"bistro",
	"bookstore",
	"boutique",
	"brasserie",
	"bus station",
	"butcher shop",
	"cafe",
	"cafeteria",
	"camera store",
	"candy shop",
	"capitol building",
	"car dealership",
	"car wash",
	"cemetary",
	"cinema",
	"city hall",
	"clinic",
	"clothing store",
	"coffee shop",
	"college",
	"community center",
	"convenience store",
	"convention center",
	"copy shop",
	"courthouse",
	"dance studio",
	"deli",
	"delicatessen",
	"department store",
	"dentist's office",
	"diner",
	"discount store",
	"doctor's office",
	"dollar store",
	"dressmaker",
	"drive-in movie",
	"drive-through",
	"drugstore",
	"electronics store",
	"fabric store",
	"factory outlet",
	"farmer's market",
	"fast food restaurant",
	"feed store",
	"fire station",
	"fix-it shop",
	"florist",
	"food court",
	"funeral home",
	"furniture store",
	"gallery",
	"game store",
	"gas station",
	"general store",
	"gift store",
	"grocery store",
	"gym",
	"gymnasium",
	"hairdresser",
	"hardware store",
	"hobby store",
	"home improvement store",
	"hotel",
	"ice cream shop",
	"inn",
	"jewelry store",
	"library",
	"lighthouse",
	"lumberyard",
	"mall",
	"market",
	"meeting house",
	"motel",
	"movie theater",
	"museum",
	"music store",
	"natural history museum",
	"nursery",
	"office building",
	"optometrist",
	"outlet store",
	"park",
	"parking garage",
	"pawnshop",
	"pet store",
	"pharmacy",
	"pizza place",
	"playground",
	"police station",
	"post office",
	"pub",
	"public garden",
	"quilt store",
	"real estate agency",
	"repair shop",
	"restaurant",
	"retailer",
	"salon",
	"saloon",
	"sandwich shop",
	"school",
	"second hand store",
	"shoe store",
	"shop",
	"soda shop",
	"sporting goods store",
	"stadium",
	"stationery store",
	"store",
	"supermarket",
	"surplus store",
	"tailor",
	"tavern",
	"tea house",
	"tearoom",
	"theater",
	"thrift store",
	"town hall",
	"toy store",
	"train station",
	"travel agent",
	"truck stop",
	"university",
	"upholstery shop",
	"video store",
	"wax museum",
	"zoo"
];
var REASON = [
	"my power makes everyone",
	"a crazy person said",
	"my best friend said",
	"my parents said",
	"my nemisis said",
	"my doctor said",
	"someone was wearing",
	"everyone was chanting",
	"I was playing a game called",
	"the place was called",
	"the internet said",
	"an old man said",
	"I hallucinated that",
	"the voice in my head said",
	"an attractive guy turned out to be",
	"an attractive girl turned out to be",
	"someone showed me",
	"long story short",
	"someone put",
	"my imaginary friend said",
	"a mysterious stranger said",
	"someone handed me",
	"I had a premonition that",
	"a booming voice said",
	"I saw",
	"I felt someone",
	"someone was eating",
	"everyone was talking about",
	"I bought",
	"I stole",
	"I bumped into",
	"the police said",
	"I tried to",
	"I starred at",
	"I started to",
	"I had to",
	"I was not",
	"the slogan was",
	"they wanted me to"
];

(function(){
	var emotion = EMOTION[Math.floor((Math.random() * EMOTION.length))].toLowerCase();
	var location = LOCATION[Math.floor((Math.random() * LOCATION.length))];
	var reason = REASON[Math.floor((Math.random() * REASON.length))];
	document.getElementById("kneejerk1").innerHTML = 
		"I felt " + emotion + " at the " + location + " because " + reason + "...";	
	reason = REASON[Math.floor((Math.random() * REASON.length))];
	document.getElementById("kneejerk2").innerHTML = 
		"I felt " + emotion + " at the " + location + " because " + reason + "...";	
	reason = REASON[Math.floor((Math.random() * REASON.length))];
	document.getElementById("kneejerk3").innerHTML = 
		"I felt " + emotion + " at the " + location + " because " + reason + "...";	
})()

